apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "annotation-admission-controller.fullname" . }}
  labels:
    {{- include "annotation-admission-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "annotation-admission-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "annotation-admission-controller.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "annotation-admission-controller.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTPS
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTPS
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTPS
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: ANNOTATIONS
              value: {{ include "annotations-to-apply" . | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /tls
      volumes:
        - name: cert
          secret:
            secretName: {{ include "annotation-admission-controller.fullname" . }}-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
