apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "annotation-admission-controller.fullname" . }}-webhook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "annotation-admission-controller.fullname" . }}
webhooks:
- name: annotate.annotation-admission-controller.gregorius.dev
  matchPolicy: Equivalent
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1"]
  rules:
  - operations:
      {{- toYaml .Values.annotate.operations | nindent 6 }}
    apiGroups:
      {{- toYaml .Values.annotate.target.apiGroups | nindent 6 }}
    apiVersions:
      {{- toYaml .Values.annotate.target.apiVersions | nindent 6 }}
    resources:
      {{- toYaml .Values.annotate.target.resources | nindent 6 }}
    scope: {{ .Values.annotate.target.scope }}
  timeoutSeconds: 20
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "annotation-admission-controller.fullname" . }}
      path: /annotate
      port: {{ .Values.service.port }}
