apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "annotation-admission-controller.fullname" . }}-webhook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "annotation-admission-controller.fullname" . }}
webhooks:
- name: annotate
  matchPolicy: Equivalent
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1"]
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: [ "CREATE", "UPDATE" ]
    resources: ["persistentvolumeclaims"]
    scope: "Namespaced"
  timeoutSeconds: 20
  clientConfig:
    service:
      namespace: {{ Release.Namespace }}
      name: {{ include "annotation-admission-controller.fullname" . }}
      path: /annotate
      port: 8000
