replicaCount: 1

image:
  registry: ghcr.io
  repository: olivergregorius/annotation-admission-controller
  tag: 0.1.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8443

clusterDomain: cluster.local

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 250m

nodeSelector: {}

tolerations: []

affinity: {}

annotate:
  target:
    # apiGroups, apiVersions, resources: endpoint definition of the resource, check the [Kubernetes API Reference](https://kubernetes.io/docs/reference/kubernetes-api/) for more information
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["persistentvolumeclaims"]
    # scope: allowed values are "Namespaced", "Cluster" or "*"
    scope: Namespaced
  # operations: allowed values are "CREATE", "UPDATE", "DELETE" or "CONNECT"
  operations: ["CREATE", "UPDATE"]
  # annotations: map of annotations to be added to the resource
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
