replicaCount: 1

image:
  registry: ghcr.io
  repository: olivergregorius/annotation-admission-controller
  tag: 0.1.7
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8443

clusterDomain: cluster.local

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 250m

nodeSelector: {}

tolerations: []

affinity: {}

annotate:
  target:
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["persistentvolumeclaims"]
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
