replicaCount: 1

image:
  registry: ghcr.io
  repository: olivergregorius/annotation-admission-controller
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    memory: 32Mi
    cpu: 100m
  limits:
    memory: 32Mi
    cpu: 100m

nodeSelector: {}

tolerations: []

affinity: {}

annotationsToApply: ""
clusterDomain: cluster.local
